<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'About' => 'О нас',
  'Accounts' => 'Учетные записи',
  'Append Child Page' => 'Добавьте Child страницу',
  'Append Sibling Page' => 'Добавьте Sibling Page',
  'Application' => 'Приложение',
  'Assignments' => 'Назначение',
  'Body' => '',
  'Browse' => 'Просматривать',
  'Browser' => 'Браузер',
  'Company groups' => 'Группы компаний',
  'Contact Us' => 'Связаться с нами',
  'Currency ' => 'Валюта',
  'Currency sources' => 'Источники Валюты',
  'DBR' => '',
  'Dashboard' => 'Панель',
  'Email' => 'Электронная почта',
  'Error' => 'Ошибка',
  'Fields with' => 'Поля с',
  'If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.' => 'Если у вас есть деловое предложение или другие вопросы, пожалуйста, заполните следующую форму, чтобы связаться с нами. Спасибо.',
  'Languages' => 'Языки',
  'List' => 'Список',
  'Local File Scan' => 'Локальное сканирование файла',
  'Login' => 'Войти',
  'Logout' => 'Выйти',
  'Media' => 'Медиа',
  'Name' => 'Название',
  'Overview' => 'Обзор',
  'Pages' => 'Страницы',
  'Permissions' => 'Права доступа',
  'Please enter the letters as they are shown in the image above.<br/>Letters are not case-sensitive.' => 'Пожалуйста, введите буквы, изображенные на картинке выше. <br/> Буквы вводятся без учета регистра.',
  'Position and Settings' => 'Положение и настройки',
  'Profile' => 'Профиль',
  'Registry' => 'Регистрация',
  'Rights' => 'Права',
  'Roles' => 'Роли',
  'Settings' => 'Настройки',
  'Sitemap' => 'Карта сайта',
  'Status flow' => 'Поток Статус',
  'Subject' => 'Тема',
  'Submit' => 'Представьте',
  'Template' => 'Шаблон',
  'Thank you for contacting us. We will respond to you as soon as possible.' => 'Благодарим Вас за обращение к нам. Мы ответим вам как можно скорее.',
  'This is a "static" page. You may change the content of this page by updating the file' => '',
  'Translation' => 'Перевод',
  'Upload' => 'Загрузить файл',
  'User' => 'Пользователь',
  'Users' => 'Пользователи',
  'Verification Code' => 'Код подтверждения',
  'Widgets' => '',
  'are required' => 'Требуются',
);
