<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Actual period' => 'Актуальный период',
  'Administration' => 'Администрация',
  'Company Custom Fields' => 'Компания Пользовательские поля',
  'Currency rates' => 'Курсы валют',
  'Daily report by Customer' => 'Ежедневный отчет по клиентами',
  'Daily report by FS' => 'Ежедневный отчет по  АЗС',
  'Invoices' => 'Счета-фактуры',
  'Payments' => 'Платежи',
  'All' => 'Все',
  'Amount' => 'Сумма',
  'Currencies' => 'Валюты',
  'Current' => 'Текущий',
  'Current Periods' => 'Периоды',
  'Daily report' => 'Ежедневный отчет',
  'Last month' => 'В прошлом месяце',
  'Last week' => 'На прошлой неделе',
  'This month' => 'В этом месяце',
  'This week' => 'На этой неделе',
  'Today' => 'Сегодня',
  'Total' => 'Итого',
  'Yesterday' => 'Вчера',
  'Actual period by company' => 'Фактический период по клиентам',
  'Actual period by station' => 'Фактический период АЗС',
  'Cars' => 'Машины',
  'Companies' => 'Компании',
  'Countries' => 'Страны',
  'Daily report by customers' => 'Ежедневный отчет по клиентам', 
  'Monthly report by customers' => 'Ежемесячный отчет по клиентам',  
  'Finances' => 'Финансы',
  'Fuel price' => 'Цены топлива',
  'Fuel statements' => 'Ведомости',
  'Fuel type' => 'Виды топлива',
  'Fueling' => 'Заправки',
  'My company' => 'Моя компания',
  'Office' => 'Офис',
  'Periods' => 'Периоды',
  'Refueling' => 'Заправки',
  'Reports' => 'Отчеты',
  'Weekly report' => 'Еженедельный отчет',
  'Monthly report by Customer' => 'Ежемесячный отчет по клиентам',
  'January' => 'Январь',
  'February' => 'Февраль',
  'March'  => 'Март',
  'April'=> 'Апрель',
  'May' => 'Май',
  'June' => 'Июнь',
  'July' =>   'Июль',
  'August' => 'Август',
  'September' => 'Сентябрь',
  'October' =>  'Октябрь',
  'November' => 'Ноябрь',
  'December' => 'Декабрь',
  'This year' => 'В этом году',
  'Last year' => 'В прошлом году' ,
  'customer office' => 'личный кабинет'  
    
);
