<?php
/**
* Message translations.
*
* This file is automatically generated by 'yiic message' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE, this file must be saved in UTF-8 encoding.
*/
return array (
  'About' => 'Apie mus',
  'Accounts' => 'Sąskaitos',
  'Append Child Page' => 'Pridėkite Child puslapį',
  'Append Sibling Page' => 'Pridėkite Sibling puslapį',
  'Application' => 'Priedas',
  'Assignments' => 'Paskirymas',
  'Body' => '',
  'Browse' => 'Naršyti',
  'Browser' => 'Naršyklė',
  'Company groups' => 'Bendrovių grupės',
  'Contact Us' => 'Susisiekite su mumis',
  'Currency ' => 'Valiuta',
  'Currency sources' => 'Valiutų šaltiniai',
  'DBR' => '',
  'Dashboard' => 'Skydas',
  'Email' => 'Elektroninis paštas',
  'Error' => 'Klaida',
  'Fields with' => 'Laukas su',
  'If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.' => 'Jeigu turite verslo pasiūlymą ar kitų klausimų, norėdami susisiekti su mumis prašome užpildyti pateiktą formą. Dėkojame.',
  'Languages' => 'Kalbos',
  'List' => 'Sąrašas',
  'Local File Scan' => 'Vietinis failo skenavimas',
  'Login' => 'Prisijungti',
  'Logout' => 'Atsijungti',
  'Media' => 'Laikmenos',
  'Name' => 'Pavadinimas',
  'Overview' => 'Peržiūra',
  'Pages' => 'Puslapiai',
  'Permissions' => 'Leidimo teisė',
  'Please enter the letters as they are shown in the image above.<br/>Letters are not case-sensitive.' => 'Prašome įvesti raides, aukščiau esančiame paveikslėlyje. <br/> Raidės įvedamos neatsižvelgiant į registrą.',
  'Position and Settings' => 'Būklė ir nustatymai',
  'Profile' => 'Profilis',
  'Registry' => 'Registracija',
  'Rights' => 'Teisės',
  'Roles' => 'Vaidmenys',
  'Settings' => 'Nustatymai',
  'Sitemap' => 'Svetainės žemėlapis',
  'Status flow' => 'Srauto būsena',
  'Subject' => 'Tema',
  'Submit' => 'Pateikti',
  'Template' => 'Šablonas',
  'Thank you for contacting us. We will respond to you as soon as possible.' => 'Dėkojame, kad norite su mumis susisiekti. Mes atsakysime jums kaip įmanoma greičiau.',
  'This is a "static" page. You may change the content of this page by updating the file' => '',
  'Translation' => 'Vertimas',
  'Upload' => 'Įkelti failą',
  'User' => 'Vartotojas',
  'Users' => 'Vartotojai',
  'Verification Code' => 'Patvirtinimo kodas',
  'Widgets' => '',
  'are required' => 'Reikalaujama',
);
