<?php
/**
* Message translations.
*
* This file is automatically generated by 'yiic message' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE, this file must be saved in UTF-8 encoding.
*/
return array (
  'Actual period' => 'Aktualus laikotarpis',
  'Administration' => 'Administracija',
  'Company Custom Fields' => 'Įprastiniai įmonės laukai',
  'Currency rates' => 'Valiutų kursai',
  'Daily report by Customer' => 'Kasdieninė ataskaita pagal klientus',
  'Daily report by FS' => 'Kasdieninė ataskaita pagal degalines',
  'Invoices' => 'Sąskaitos-faktūros',
  'Payments' => 'Mokėjimai',
  'All' => 'Visi',
  'Amount' => 'Suma',
  'Currencies' => 'Valiutos',
  'Current' => 'Einamasis',
  'Current Periods' => 'Laikotarpis',
  'Daily report' => 'Kasdieninė ataskaita',
  'Last month' => 'Praeito mėnesio',
  'Last week' => 'Praeita savaite',
  'This month' => 'Šį mėnesį',
  'This week' => 'Šią savaitę',
  'Today' => 'Šiandien',
  'Total' => 'Viso',
  'Yesterday' => 'Vakar',
  'Actual period by company' => 'Faktinis laikotarpis pagal klientus',
  'Actual period by station' => 'Faktinis laikotarpis pagal degalines',
  'Cars' => 'Automobiliai',
  'Companies' => 'Bendrovės',
  'Countries' => 'Šalys',
  'Finances' => 'Finansai',
  'Fuel price' => 'Kuro kainos',
  'Fuel statements' => 'Sąrašai',
  'Fuel type' => 'Kuro rūšys',
  'Fueling' => 'Kuro pylimas',
  'My company' => 'Mano bendrovė',
  'Office' => 'Ofisas',
  'Periods' => 'Laikotarpiai',
  'Refueling' => 'Kuro pylimai',
  'Reports' => 'Ataskaitos',
  'Weekly report' => 'Kasdieninė ataskaita',
  'Monthly report by Customer' => 'Mėnesio ataskaita pagal klientus',
  'January' => 'Sausis',
  'February' => 'Vasaris',
  'March' => 'Kovas',
  'April'=> 'Balandis',
  'May' => 'Gegužė',
  'June' => 'Birželis',
  'July' => 'Liepa',
  'August' => 'Rugpjūtis',
  'September' => 'Rugsėjis',
  'October' => 'Spalis',
  'November' => 'Lapkritis',
  'December' => 'Gruodis',
  'This year' => 'Šiais metais',
  'Last year' => 'Praeitais metais',
  'customer office' => 'Asmeninis kabinetas'  ,
  'Click to edit' => 'Paspauskite tam, kad pakeisti'
    
);

