<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Actual period' => 'Aktuālais periods',
  'Actual period by company' => 'Aktuālais periods/Uzņēmumi',
  'Actual period by station' => 'Aktuālais periods/DUS',
  'Administration' => 'Administrēšana',
  'Cars' => 'Auto',
  'Companies' => 'Uzņēmumi',
  'Company Custom Fields' => 'Uzņemumu definētie lauki',
  'Countries' => 'Valstis',
  'Currency rates' => 'Valūtas kurss',
  'Daily report by Customer' => 'Ikdienas atskaite pa klientiem',
  'Daily report by FS' => 'Ikdienas atskaite pa DUSiem',
  'Finances' => 'Finances',
  'Fuel price' => 'Degvielas cenas',
  'Fuel statements' => 'DUS atskaites',
  'Fuel type' => 'Degvielas tips',
  'Fueling' => 'Uzpildīšana',
  'Invoices' => 'Rēķini',
  'My company' => 'Mans uzņemums',
  'Office' => 'Birojs',
  'Payments' => 'Maksājumi',
  'Periods' => 'Periodi',
  'Exp.Positons' => 'Izd.Pozīcijas',
  'Refueling' => 'Uzpildīšana',
  'Reports' => 'Atskaites',
  'Weekly report' => 'Nedēļu atskaites',
  'Trailers' => 'Piekabes',
  'Trucks' => 'Vilcēji',
  'Truck/trailer services' => 'Vilc./Piek. darbi',
  'Truck/trailer doc. types' => 'Vilc./Piek. dok. veidi',
);